version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"

  app:
    depends_on:
      - mysql
      - postgresql
    image: apiw1
    build: .
    restart: unless-stopped
    command: npm start
    environment:
    - CHAVE_SECRETA=CHAVE_AQUI
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true